# Generated by Django 3.0.3 on 2020-04-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
        ('todo', '0006_auto_20200415_2127'),
    ]

    operations = [
    ]
