# Generated by Django 3.0.2 on 2020-03-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0003_auto_20200302_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpa',
            name='GPA',
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer Session', 'Summer Session'), ('J-Term', 'J-Term')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
