# Generated by Django 3.0.2 on 2020-04-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0004_auto_20200302_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPA',
        ),
    ]
