# Generated by Django 3.0.3 on 2020-04-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0005_delete_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(choices=[(2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015)]),
        ),
    ]
