# Generated by Django 3.0.2 on 2020-04-16 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0005_delete_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='credit_hours',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(choices=[(2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015)]),
        ),
    ]
