# Generated by Django 3.0.3 on 2020-04-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0007_auto_20200422_1750'),
        ('gpa', '0006_auto_20200415_2127'),
    ]

    operations = [
    ]
