# Generated by Django 3.0.3 on 2020-04-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0007_auto_20200422_1750'),
        ('gpa', '0007_auto_20200416_2334'),
    ]

    operations = [
    ]
