# Generated by Django 3.0.3 on 2020-04-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0008_class_user'),
        ('gpa', '0008_merge_20200422_2209'),
    ]

    operations = [
    ]
