# Generated by Django 3.0.3 on 2020-04-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpa', '0009_merge_20200427_1623'),
        ('gpa', '0008_merge_20200424_2258'),
    ]

    operations = [
    ]
